default:

  # project configuration
  project_name             : "census_demo"
  job_output               : "jobs/local"
  exclude                  : "analysis"

  # packrat configuration
  packrat_enabled          : true

  # Inputs (downsampled data for local development)
  eval_file                : "gs://rstudio-cloudml-demo-ml/census/data/local.adult.test"
  train_file               : "gs://rstudio-cloudml-demo-ml/census/data/local.adult.data"

  # Training parameters
  estimator_embedding_size : 8
  estimator_hidden_units   : [100, 70, 50, 25]
  eval_num_epochs          : 10
  eval_batch_size          : 40
  eval_delay_secs          : 10
  eval_steps               : 100
  train_num_epochs         : 10
  train_batch_size         : 40
  train_steps              : 10

cloudml:

  # Inputs
  eval_file                : "gs://rstudio-cloudml-demo-ml/census/data/adult.test"
  train_file               : "gs://rstudio-cloudml-demo-ml/census/data/adult.data"

  # Outputs
  job_output               : "gs://rstudio-cloudml-demo-ml/census/jobs"

  # Training parameter overrides
  eval_batch_size          : 100
  train_batch_size         : 100
