default:

  # Inputs
  eval_file                : "gs://tf-ml-workshop/widendeep/adult.data"
  train_file               : "gs://tf-ml-workshop/widendeep/adult.test"
  
  # Outputs
  job_dir                  : jobs

  # Parameters for training routines
  estimator_embedding_size : 8
  estimator_hidden_units   : [100, 70, 50, 25]
  eval_num_epochs          : 10
  eval_batch_size          : 40
  eval_delay_secs          : 10
  eval_steps               : 100
  train_num_epochs         : 10
  train_batch_size         : 40
  train_steps              : 10

gcloud:

  # Inputs
  eval_file                : "gs://tf-ml-workshop/widendeep/adult.data"
  train_file               : "gs://tf-ml-workshop/widendeep/adult.test"
  
  # Outputs (to run within another gcloud account, substitute your own buckets)
  job_dir                  : "gs://rstudio-cloudml-demo-ml/census/jobs"
  staging_bucket           : "gs://rstudio-cloudml-demo-ml"

  # Overrides for parameters
  eval_num_epochs          : 100
  train_num_epochs         : 100
