default:

  # Inputs (downsampled data for local development)
  eval_file                : "local/data/local.adult.test"
  train_file               : "local/data/local.adult.data"

  # Outputs (write to local jobs directory)
  job_dir                  : "local/jobs"

  # Parameters for training routines
  estimator_embedding_size : 8
  estimator_hidden_units   : [100, 70, 50, 25]
  eval_num_epochs          : 10
  eval_batch_size          : 40
  eval_delay_secs          : 10
  eval_steps               : 100
  train_num_epochs         : 10
  train_batch_size         : 40
  train_steps              : 10

gcloud:

  # Inputs
  eval_file                : "gs://tf-ml-workshop/widendeep/adult.data"
  train_file               : "gs://tf-ml-workshop/widendeep/adult.test"

  # Outputs (to run within another gcloud account, substitute your own buckets)
  job_dir                  : !expr cloudml::job_dir("gs://rstudio-cloudml-demo-ml/census/jobs")
  staging_bucket           : "gs://rstudio-cloudml-demo-ml"

  # Overrides for training parameters
  eval_num_epochs          : 25
  train_num_epochs         : 25
